### ISSUE TITLE
empty(ish) files after install - error on startup

### ISSUE THREAD

**Issue by magwa101** [ershov/reaper64#1]
Just downloaded using reapack using suggested URL on youtube:
https://raw.githubusercontent.com/ershov/reaper64/main/index.xml

When running I get (paraphrased):
"error importing no @init or other code"

All files in:
JSFX/ersh_agc-inc

Appear empty:
-rw-r--r--  1 magwa101  staff  34 Dec 18 09:57 ersh_alloc.jsfx-inc
-rw-r--r--  1 magwa101  staff  34 Dec 18 09:57 ersh_deque.jsfx-inc
-rw-r--r--  1 magwa101  staff  37 Dec 18 09:57 ersh_graphlib.jsfx-inc
-rw-r--r--  1 magwa101  staff  40 Dec 18 09:57 ersh_ringbuf_abs.jsfx-inc

Bad install?

**Comment by fmonk** [comment]
I had the same issue with the current release, I installed the previous version (1.1.1) and it's working.

**Comment by ershov** [comment]
Hey thanks guys for bringing this up. That's a quirk of reapack-index. Now it's fixed in v1.2.1. please check it out.
